const QuoteActionTypes= {

    GENERATE_RANDOM_QUOTE_ID: 'GENERATE_RANDOM_QUOTE_ID',
    
    SET_LIKED_QUOTE: 'SET_LIKED_QUOTE',
    
    SET_INSPIRATIONAL_QUOTE: 'SET_INSPIRATIONAL_QUOTE',
    SET_INSIGHTFUL_QUOTE: 'SET_INSIGHTFUL_QUOTE',
    
    ADD_QUOTE_CARD: 'ADD_QUOTE_CARD',

}

export default QuoteActionTypes;