const QuoteActionTypes= {
    GENERATE_RANDOM_COLOR: 'GENERATE_RANDOM_COLOR',

    ADD_QUOTE_TO_DATA_BASE: 'ADD_QUOTE_TO_DATA_BASE',
    
    SET_LIKED_QUOTE: 'SET_LIKED_QUOTE',
    
    SET_INSPIRATIONAL_QUOTE: 'SET_INSPIRATIONAL_QUOTE'
}

export default QuoteActionTypes;